name: base

channels:
  - conda-forge

dependencies:
  - python=3.10
  - gitpython
  - git
  - jupyterlab<4.0
  - jupyterlab-git
  - access
  - cartopy
  - contextily
  - dask
  - dask-ml
  - datashader
  - esda
  - fiona=1.8.22
  - geopandas
  - geojson
  - geoplot
  - geoviews
  - hvplot
  - inequality
  # Solving KeplerGL issues: https://github.com/keplergl/kepler.gl/issues/1993
  - ipywidgets=7.8.0
  - keplergl
  - mapclassify
  - matplotlib
  - mesa
  - mgwr
  - momepy
  - movingpandas
  - networkx
  # - openjdk
  - openpyxl
  - osmnx
  - palettable
  - pandana
  - plotly
  - pointpats
  - pyrosm
  - pysal
  - python-igraph
  - r5py
  - r5py.sampledata.helsinki>=0.1.1dev2
  - r5py.sampledata.sao_paulo>=0.1.1dev2
  - scipy
  - scikit-image
  - scikit-learn
  - scikit-mobility
  - segregation
  - simpy
  - spint
  - splot
  - spreg
  - statsmodels
  - seaborn
  - pandas
  - urbanaccess
  # Solving KeplerGL issues: https://github.com/keplergl/kepler.gl/issues/1993
  - widgetsnbextension=3.6.5
  - nose
  - jinja2