name: base

channels:
  - conda-forge

dependencies:
  - python=3.9
  - access
  - bokeh
  - clustergram
  - contextily
  - dash
  - dask
  - dask-ml
  - datashader
  - earthpy
  - esda
  - folium
  - geocube
  - geojson
  - geopandas
  - geoplot
  - geopy
  - giddy
  - gstools
  - h3-py
  - hdbscan
  - hvplot
  - inequality
  - jupyterlab=3.0.6
  - jupyterlab-git
  - legendgram
  - mamba
  - mapclassify
  - matplotlib
  - mesa
  - mgwr
  - momepy
  - movingpandas
  - mplleaflet
  - networkx
  - openpyxl
  - osmnx
  - palettable
  - pandana
  - pandas
  - plotly_express
  - pointpats
  - polyline
  - pyarrow
  - pygeos
  - pykrige
  - pyrosm
  - pysal
  - python-igraph
  - rasterio
  - rasterstats
  - richdem
  - scikit-image
  - scikit-learn
  - scikit-mobility
  - scipy
  - seaborn
  - segregation
  - spaghetti
  - spint
  - splot
  - spreg
  - sqlalchemy
  - statsmodels
  - tobler
  - tqdm
  - urbanaccess
  - vaex
  - vaex-arrow
  - xarray
  - xarray_leaflet
  - xarray-spatial
  - xlrd
  - xlsxwriter
