name: base

channels:
  - conda-forge

dependencies:
  - python=3.11
  - access
  - bokeh
  - clustergram
  - contextily
  - dash
  - dask
  - dask-ml
  - datashader
  - earthpy
  - esda
  - folium
  - geocube
  - geojson
  - geopandas
  - geoplot
  - geopy
  - giddy
  - gstools
  - h3-py
  - hvplot
  - inequality
  - jupyterlab
  - jupyterlab-git
  - legendgram
  - mamba
  - mapclassify
  - matplotlib
  - mesa
  - mgwr
  - momepy
  - movingpandas
  - mplleaflet
  - networkx
  - openpyxl
  - openjdk
  - osmnx
  - palettable
  - pandana
  - pandas
  - plotly_express
  - pointpats
  - polyline
  - pyarrow
  - pygeos
  - pyinterpolate
  - pykrige
  # - pyrosm
  - pysal
  - python-igraph
  - r5py
  - rasterio
  - rasterstats
  - richdem
  - rioxarray
  - scikit-image
  - scikit-learn
  - scikit-mobility
  - scipy
  - seaborn
  - segregation
  - spaghetti
  - spint
  - splot
  - spreg
  - sqlalchemy
  - statsmodels
  - tobler
  - tqdm
  - urbanaccess
  # - vaex
  # - vaex-arrow
  - xarray
  - xarray_leaflet
  - xarray-spatial
  - xlrd
  - xlsxwriter
